import React from 'react';
import { Navbar } from './Navbar';
import { AlertTriangle, Brain, Fingerprint, BarChart3, Shield, Users } from 'lucide-react';

export function About() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-[#1a237e] via-[#4a148c] to-[#880e4f]">
      <Navbar userEmail={null} />
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="text-center mb-16">
          <h1 className="text-4xl font-bold text-white mb-4">Understanding AI's Impact</h1>
          <p className="text-violet-200 text-lg max-w-3xl mx-auto">
            Exploring the dual nature of artificial intelligence and its profound effects on our society
          </p>
        </div>

        {/* Statistics Section */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
          <div className="bg-white/5 backdrop-blur-lg rounded-2xl p-8 border border-violet-500/20">
            <BarChart3 className="h-12 w-12 text-purple-300 mb-4" />
            <h3 className="text-2xl font-bold text-white mb-2">90%</h3>
            <p className="text-violet-200">of online content will be AI-generated by 2026</p>
          </div>
          <div className="bg-white/5 backdrop-blur-lg rounded-2xl p-8 border border-violet-500/20">
            <Users className="h-12 w-12 text-purple-300 mb-4" />
            <h3 className="text-2xl font-bold text-white mb-2">66%</h3>
            <p className="text-violet-200">of people cannot distinguish AI from human content</p>
          </div>
          <div className="bg-white/5 backdrop-blur-lg rounded-2xl p-8 border border-violet-500/20">
            <Shield className="h-12 w-12 text-purple-300 mb-4" />
            <h3 className="text-2xl font-bold text-white mb-2">$20B</h3>
            <p className="text-violet-200">estimated damages from deepfake fraud in 2024</p>
          </div>
        </div>

        {/* Main Content Sections */}
        <div className="space-y-16">
          {/* The Rise of AI Content */}
          <section className="bg-white/5 backdrop-blur-lg rounded-2xl p-8 border border-violet-500/20">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
              <div>
                <Brain className="h-12 w-12 text-purple-300 mb-4" />
                <h2 className="text-3xl font-bold text-white mb-4">The Rise of AI Content</h2>
                <p className="text-violet-200 mb-4">
                  Artificial Intelligence has revolutionized content creation, enabling the production of text, images, and videos at an unprecedented scale. While this brings incredible opportunities for creativity and efficiency, it also raises important questions about authenticity and trust.
                </p>
                <ul className="text-violet-200 space-y-2">
                  <li className="flex items-center space-x-2">
                    <span className="w-2 h-2 bg-purple-400 rounded-full"></span>
                    <span>Automated content generation</span>
                  </li>
                  <li className="flex items-center space-x-2">
                    <span className="w-2 h-2 bg-purple-400 rounded-full"></span>
                    <span>Enhanced productivity tools</span>
                  </li>
                  <li className="flex items-center space-x-2">
                    <span className="w-2 h-2 bg-purple-400 rounded-full"></span>
                    <span>Creative assistance platforms</span>
                  </li>
                </ul>
              </div>
              <div className="bg-gradient-to-br from-purple-900/50 to-pink-900/50 rounded-xl h-64 flex items-center justify-center overflow-hidden">
                <img 
                  src="https://static.semrush.com/blog/uploads/media/85/84/8584c8e515fef9289a196a80b49b3371/dc41a201326714bbd26590ddd16bb999/original.png" 
                  alt="Rise of AI"
                  className="w-full h-full object-cover"
                />
              </div>
            </div>
          </section>

          {/* The Dark Side of AI */}
          <section className="bg-white/5 backdrop-blur-lg rounded-2xl p-8 border border-violet-500/20">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
              <div className="order-2 md:order-1 bg-gradient-to-br from-purple-900/50 to-pink-900/50 rounded-xl h-64 flex items-center justify-center overflow-hidden">
                <img 
                  src="https://cdn.statcdn.com/Infographic/images/normal/32112.jpeg" 
                  alt="AI Threat"
                  className="w-full h-full object-cover"
                />
              </div>
              <div className="order-1 md:order-2">
                <AlertTriangle className="h-12 w-12 text-purple-300 mb-4" />
                <h2 className="text-3xl font-bold text-white mb-4">The Dark Side of AI</h2>
                <p className="text-violet-200 mb-4">
                  The rise of AI-generated content has brought significant challenges, including deepfakes, misinformation, and the potential for fraud. These technologies can be misused to create convincing but false content that can harm individuals and society.
                </p>
                <ul className="text-violet-200 space-y-2">
                  <li className="flex items-center space-x-2">
                    <span className="w-2 h-2 bg-purple-400 rounded-full"></span>
                    <span>Deepfake manipulation</span>
                  </li>
                  <li className="flex items-center space-x-2">
                    <span className="w-2 h-2 bg-purple-400 rounded-full"></span>
                    <span>Misinformation spread</span>
                  </li>
                  <li className="flex items-center space-x-2">
                    <span className="w-2 h-2 bg-purple-400 rounded-full"></span>
                    <span>Identity theft risks</span>
                  </li>
                </ul>
              </div>
            </div>
          </section>

          {/* Our Solution */}
          <section className="bg-white/5 backdrop-blur-lg rounded-2xl p-8 border border-violet-500/20">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
              <div>
                <Fingerprint className="h-12 w-12 text-purple-300 mb-4" />
                <h2 className="text-3xl font-bold text-white mb-4">Our Solution</h2>
                <p className="text-violet-200 mb-4">
                  We're committed to helping users identify AI-generated content through advanced detection technologies. Our platform provides tools to analyze text, images, and audio, helping maintain trust and authenticity in digital content.
                </p>
                <ul className="text-violet-200 space-y-2">
                  <li className="flex items-center space-x-2">
                    <span className="w-2 h-2 bg-purple-400 rounded-full"></span>
                    <span>Advanced detection algorithms</span>
                  </li>
                  <li className="flex items-center space-x-2">
                    <span className="w-2 h-2 bg-purple-400 rounded-full"></span>
                    <span>Multi-format analysis</span>
                  </li>
                  <li className="flex items-center space-x-2">
                    <span className="w-2 h-2 bg-purple-400 rounded-full"></span>
                    <span>Real-time verification</span>
                  </li>
                </ul>
              </div>
              <div className="bg-gradient-to-br from-purple-900/50 to-pink-900/50 rounded-xl h-64 flex items-center justify-center">
               <img 
                  src="https://blog.metaphysic.ai/wp-content/uploads/2024/06/fake-inversion-MAIN.jpg" 
                  alt="Rise of AI"
                  className="w-full h-full object-cover"
                />
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}